{% set version = "2.0.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nlmixr2data
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nlmixr2data_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nlmixr2data/nlmixr2data_{{ version }}.tar.gz
  sha256: 8f8b544a01e01319f8b66eb306f7f164afec3b82098b041337fa2750baae3e54

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('nlmixr2data')"           # [not win]
    - "\"%R%\" -e \"library('nlmixr2data')\""  # [win]

about:
  home: https://nlmixr2.github.io/nlmixr2data/
  dev_url: https://github.com/nlmixr2/nlmixr2data/
  license: GPL-3.0-or-later
  summary: Datasets for 'nlmixr2' and 'rxode2'. 'nlmixr2' is used for fitting and comparing nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential
    equation solving is by compiled C code provided in the 'rxode2' package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: nlmixr2data
# Title: Nonlinear Mixed Effects Models in Population PK/PD, Data
# Version: 2.0.8
# Authors@R: c(person("Matthew","Fidler", role = c("aut", "cre"), email = "matthew.fidler@gmail.com", comment=c(ORCID="0000-0001-8538-6691")), person("Rik", "Schoemaker", role = "ctb", email = "rik.schoemaker@occams.com", comment=c(ORCID="0000-0002-7538-3005")), person("Thierry", "Wendling", role = "ctb"), person("Ted","Grasella", role="ctb"), person("C", "Weil", role="ctb"), person("Yaning", "Wang", role="ctb"), person("R", "O'Reilly", role="ctb"), person("David", "D'Argenio", role="ctb"), person("", "Rodriguez-Vera", role="ctb"), person("D", "Gaver", role="ctb"), person("Yuan", "Xiong", role="ctb"), person("Wenping", "Wang", role = "aut", email = "wwang8198@gmail.com") )
# Description: Datasets for 'nlmixr2' and 'rxode2'. 'nlmixr2' is used for fitting and comparing nonlinear mixed-effects models in differential equations with flexible dosing information commonly seen in pharmacokinetics and pharmacodynamics (Almquist, Leander, and Jirstrand 2015 <doi:10.1007/s10928-015-9409-1>). Differential equation solving is by compiled C code provided in the 'rxode2' package (Wang, Hallow, and James 2015 <doi:10.1002/psp4.12052>).
# License: GPL (>= 3)
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Depends: R (>= 2.10)
# LazyData: true
# BugReports: https://github.com/nlmixr2/nlmixr2data/issues/
# URL: https://nlmixr2.github.io/nlmixr2data/, https://github.com/nlmixr2/nlmixr2data/
# NeedsCompilation: no
# Packaged: 2023-08-30 22:55:52 UTC; matt
# Author: Matthew Fidler [aut, cre] (<https://orcid.org/0000-0001-8538-6691>), Rik Schoemaker [ctb] (<https://orcid.org/0000-0002-7538-3005>), Thierry Wendling [ctb], Ted Grasella [ctb], C Weil [ctb], Yaning Wang [ctb], R O'Reilly [ctb], David D'Argenio [ctb], Rodriguez-Vera [ctb], D Gaver [ctb], Yuan Xiong [ctb], Wenping Wang [aut]
# Maintainer: Matthew Fidler <matthew.fidler@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-08-30 23:30:02 UTC
